FROM node:16.13.0 AS builder
WORKDIR /app
COPY ./package.json ./
COPY ./package-lock.json ./
COPY ./vite.config.js ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:16.13-alpine
WORKDIR /app
EXPOSE 8080
COPY --chown=node:node --from=builder /app ./
USER node
CMD ["npm","run","dev"]